# Quarkus
quarkus.http.port=${PORT:8080}
quarkus.hibernate-orm.database.generation=update

#CORS
quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:3000}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:localpassword}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/contaquiz_db}

# JWT
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:META-INF/public_key.pem}
mp.jwt.verify.issuer=${JWT_ISSUER:ContaQuiz}
smallrye.jwt.sign.key.location=${JWT_SIGN_KEY_LOCATION:META-INF/private_key.pem}

# Argon2id - parametros OWASP 2024
app.security.argon2.iterations=${ARGON2_ITERATIONS:3}
app.security.argon2.memory=${ARGON2_MEMORY:65536}
app.security.argon2.parallelism=${ARGON2_PARALLELISM:4}
app.security.argon2.hash-length=${ARGON2_HASH_LENGTH:32}
app.security.argon2.salt-length=${ARGON2_SALT_LENGTH:16}
